(function () {
  'use strict'

  function buildMockLessonSchedule() {
    const models = window.LessonRadialModels
    return models.normalizeDaySchedule({
      id: 'radial-mock-2026-07-05',
      date: '2026-07-05',
      title: 'Domenica tipo',
      startTime: '07:00',
      endTime: '23:00',
      events: [
        {
          id: 'prep-0800',
          title: 'Preparazione materiali',
          type: 'unavailable',
          startTime: '08:00',
          endTime: '09:00',
          locationName: 'Base operativa',
          status: 'planned',
          icon: 'tool',
          primaryGoal: 'Preparare conetti, protezioni e scaletta esercizi.',
          materials: ['conetti', 'cinesini', 'kit protezioni'],
          checklist: ['Controllo materiali', 'Verifica meteo', 'Note lezioni precedenti'],
        },
        {
          id: 'lesson-0930-principiante',
          title: 'Lezione singola principiante',
          type: 'lesson',
          startTime: '09:30',
          endTime: '10:30',
          locationName: 'Parco Sempione',
          status: 'planned',
          icon: 'user',
          studentIds: ['mock-student-ada'],
          studentNames: ['Ada Rossi'],
          primaryGoal: 'Stabilizzare posizione base e prime spinte controllate.',
          skills: ['posizione base', 'limone', 'frenata a limone'],
          exercises: ['andata e ritorno su linea', 'limoni lenti', 'stop progressivo'],
          materials: ['6 conetti', 'linea a terra'],
          instructorNotes: 'Tenere ritmo basso e rinforzare sguardo avanti.',
        },
        {
          id: 'travel-1030',
          title: 'Spostamento verso CityLife',
          type: 'travel',
          startTime: '10:30',
          endTime: '11:00',
          locationName: 'Sempione -> CityLife',
          status: 'planned',
          icon: 'route',
        },
        {
          id: 'lesson-1100-doppia',
          title: 'Lezione doppia',
          type: 'lesson',
          startTime: '11:00',
          endTime: '12:30',
          locationName: 'CityLife',
          status: 'planned',
          icon: 'users',
          studentIds: ['mock-student-luca', 'mock-student-marta'],
          studentNames: ['Luca Bianchi', 'Marta Verdi'],
          primaryGoal: 'Coordinare traiettorie condivise e curve ampie.',
          skills: ['curve a 8', 'passo incrociato', 'monopedale'],
          exercises: ['otto largo', 'incrociato assistito', 'tenuta monopedale 5 secondi'],
          materials: ['8 conetti', 'area libera'],
          instructorNotes: 'Separare corsie se uno dei due perde stabilita.',
        },
        {
          id: 'break-1230',
          title: 'Pausa pranzo',
          type: 'break',
          startTime: '12:30',
          endTime: '14:00',
          locationName: 'Zona Portello',
          status: 'planned',
          icon: 'pause',
        },
        {
          id: 'free-1500',
          title: 'Slot libero',
          type: 'free_slot',
          startTime: '15:00',
          endTime: '16:00',
          locationName: 'Da assegnare',
          status: 'planned',
          icon: 'plus',
          primaryGoal: 'Finestra utile per recupero lezione o follow-up.',
        },
        {
          id: 'lesson-1630-gruppo-bambini',
          title: 'Gruppo bambini',
          type: 'lesson',
          startTime: '16:30',
          endTime: '18:00',
          locationName: 'Piazza Gae Aulenti',
          status: 'planned',
          icon: 'group',
          studentIds: ['mock-group-kids'],
          studentNames: ['Gruppo bambini'],
          primaryGoal: 'Controllo ritmo, gioco tecnico e frenata sicura.',
          skills: ['posizione base', 'limone', 'frenata a limone', 'curve a 8'],
          exercises: ['staffetta con conetti', 'slalom morbido', 'stop a bersaglio'],
          materials: ['12 conetti', 'pettorine', 'gesso'],
          instructorNotes: 'Chiudere con esercizio breve di attenzione e defaticamento.',
        },
        {
          id: 'lesson-1830-avanzata',
          title: 'Lezione avanzata',
          type: 'lesson',
          startTime: '18:30',
          endTime: '19:30',
          locationName: 'Bicocca',
          status: 'planned',
          icon: 'bolt',
          studentIds: ['mock-student-nora'],
          studentNames: ['Nora Galli'],
          primaryGoal: 'Consolidare transizioni e controllo fakie.',
          skills: ['T-stop', 'passo incrociato', 'fakie', 'monopedale'],
          exercises: ['T-stop da velocita media', 'fakie controllato', 'incrociato su cerchio stretto'],
          materials: ['10 conetti', 'marker direzione'],
          instructorNotes: 'Verificare affaticamento caviglia destra prima del blocco fakie.',
        },
        {
          id: 'followup-2000',
          title: 'Note e follow-up',
          type: 'unavailable',
          startTime: '20:00',
          endTime: '20:30',
          locationName: 'Remoto',
          status: 'planned',
          icon: 'note',
          primaryGoal: 'Aggiornare appunti operativi e prossimi obiettivi.',
          checklist: ['Aggiorna progressi', 'Invia note sintetiche', 'Prepara prossima lezione'],
        },
      ],
    })
  }

  window.MockLessonSchedule = {
    buildMockLessonSchedule,
  }
})()
